[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
authors = ["Ziyi Zhang <ziyi.zhang@intel.com>"]
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.*"
quote = "1.*"
syn = { version = "2.*", features = ["full"] }
